version: "3"

services:
  web:
    build: .
    environment:
      PYTHONUNBUFFERED: 1 # to see print outputs in shell
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: mypassword
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: